# -*- coding: utf-8 -*-
"""Assignment4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UhfbRElwQ6PYz7lUKAVHXsBfy2-9Remx

**Question 1 : Create an object named student with the following properties: ● name: "Rahul" ● age: 21 ● courses: an array containing "Math", "Physics", and "Chemistry" Then, perform the following operations: 1. Add a new property grade with the value "A". 2. Update the age to 22. 3. Delete the courses property.**

**Answer:**
// Step 1: Create the student object
let student = {
  name: "Rahul",
  age: 21,
  courses: ["Math", "Physics", "Chemistry"]
};

console.log("Initial Object:", student);

// Step 2: Add a new property 'grade'
student.grade = "A";

// Step 3: Update the age to 22
student.age = 22;

// Step 4: Delete the 'courses' property
delete student.courses;

console.log("Final Object:", student);

**Question 2: Write a function checkEligibility that takes an age as a parameter and returns: ● "Eligible" if age is 18 or above ● "Not Eligible" if age is below 18 Use an if-else statement.**

**Answer:**
function checkEligibility(age) {
  if (age >= 18) {
    return "Eligible";
  } else {
    return "Not Eligible";
  }
}

// Example usage:
console.log(checkEligibility(20)); // Eligible
console.log(checkEligibility(15)); // Not Eligible

**Question 3: Write a function getDayName that takes a number (1-7) and returns the corresponding day of the week. Use a switch statement.**

**Answer:**
function getDayName(dayNumber) {
  let dayName;

  switch (dayNumber) {
    case 1:
      dayName = "Sunday";
      break;
    case 2:
      dayName = "Monday";
      break;
    case 3:
      dayName = "Tuesday";
      break;
    case 4:
      dayName = "Wednesday";
      break;
    case 5:
      dayName = "Thursday";
      break;
    case 6:
      dayName = "Friday";
      break;
    case 7:
      dayName = "Saturday";
      break;
    default:
      dayName = "Invalid day number";
  }

  return dayName;
}

// Example usage:
console.log(getDayName(1)); // Sunday
console.log(getDayName(5)); // Thursday
console.log(getDayName(8)); // Invalid day number

**Question 4: Rewrite the checkEligibility function from Question 2 using the ternary operator.**

**Answer:**
function checkEligibility(age) {
  return age >= 18 ? "Eligible" : "Not Eligible";
}

// Example usage:
console.log(checkEligibility(20)); // Eligible
console.log(checkEligibility(15)); // Not Eligible

**Question 5: Given an array numbers = [1, 2, 3, 4, 5], perform the following: 1. Use a for loop to print each number. 2. Use a while loop to print each number. 3. Use a for-in loop to print each index. 4. Use a for-of loop to print each number.**

**Answer:**
let numbers = [1, 2, 3, 4, 5];

// 1. For loop to print each number
console.log("For loop:");
for (let i = 0; i < numbers.length; i++) {
  console.log(numbers[i]);
}

// 2. While loop to print each number
console.log("While loop:");
let i = 0;
while (i < numbers.length) {
  console.log(numbers[i]);
  i++;
}

// 3. For-in loop to print each index
console.log("For-in loop (indexes):");
for (let index in numbers) {
  console.log(index);
}

// 4. For-of loop to print each number
console.log("For-of loop:");
for (let num of numbers) {
  console.log(num);
}

**Question 6: Explain what functions are in JavaScript and provide an example of a function that adds two numbers.**

**Answer:**
function addNumbers(a, b) {
  return a + b;
}

// Example usage:
console.log(addNumbers(5, 3)); // 8
console.log(addNumbers(10, 20)); // 30

**Question 7: Convert the add function from Question 6 into an arrow function.**

**Answer:**

const addNumbers = (a, b) => {
  return a + b;
};

// Example usage:
console.log(addNumbers(5, 3));   // 8
console.log(addNumbers(10, 20)); // 30

**Question 8: Write a function greet that takes a name and a callback function. The greet function should call the callback with the name.**

**Answer:**
function greet(name, callback) {
  // call the callback function with the name
  callback(name);
}

// Example callback function
function sayHello(person) {
  console.log("Hello, " + person + "!");
}

// Example usage
greet("Rahul", sayHello);

**Question 9: Given the array: const fruits = ["apple", "banana", "cherry"]; 1. What is the length of the array? 2. Add "date" to the end of the array using the length property.**

**Answer:**
const fruits = ["apple", "banana", "cherry"];

// 1. Length of the array
console.log("Length of fruits array:", fruits.length); // 3

// 2. Add "date" to the end using the length property
fruits[fruits.length] = "date";

console.log("Updated fruits array:", fruits);

**Question 10: Given the string text = " Hello World! ", perform the following: 1. Trim the whitespace. 2. Convert to uppercase. 3. Check if it includes "World".**

**Answer:**

let text = " Hello World! ";

// 1. Trim the whitespace
let trimmedText = text.trim();
console.log("Trimmed text:", trimmedText); // "Hello World!"

// 2. Convert to uppercase
let upperText = trimmedText.toUpperCase();
console.log("Uppercase text:", upperText); // "HELLO WORLD!"

// 3. Check if it includes "World"
let includesWorld = trimmedText.includes("World");
console.log("Includes 'World'? :", includesWorld); // true

**Question 11: Given the array numbers = [1, 2, 3, 4, 5], perform the following: 1. Add 6 to the end. 2. Remove the first element. 3. Find the index of 4. 4. Check if all numbers are greater than 0.**

**Answer:**

let numbers = [1, 2, 3, 4, 5];

// 1. Add 6 to the end
numbers.push(6);
console.log("After adding 6:", numbers); // [1, 2, 3, 4, 5, 6]

// 2. Remove the first element
numbers.shift();
console.log("After removing first element:", numbers); // [2, 3, 4, 5, 6]

// 3. Find the index of 4
let indexOfFour = numbers.indexOf(4);
console.log("Index of 4:", indexOfFour); // 2

// 4. Check if all numbers are greater than 0
let allGreaterThanZero = numbers.every(num => num > 0);
console.log("All numbers > 0?", allGreaterThanZero); // true
"""